# Generated by Django 5.2.8 on 2026-05-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZebricekPozice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozice', models.PositiveIntegerField(unique=True)),
                ('hrac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zebricek_data', to='tenis_app.hrac')),
            ],
            options={
                'verbose_name': 'Pozice v žebříčku',
                'verbose_name_plural': 'Pozice v žebříčku',
                'ordering': ['pozice'],
            },
        ),
    ]
