# Generated by Django 5.2.8 on 2026-01-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('klub', models.CharField(blank=True, max_length=100)),
                ('body', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sety_domaci', models.IntegerField(default=0)),
                ('sety_hoste', models.IntegerField(default=0)),
                ('skore_detail', models.CharField(blank=True, max_length=100)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('odehrano', models.BooleanField(default=False)),
                ('hrac_domaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci', to='tenis_app.hrac')),
                ('hrac_hoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoste', to='tenis_app.hrac')),
            ],
        ),
    ]
