# Generated by Django 5.2.8 on 2026-05-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno a příjmení')),
                ('klub', models.CharField(blank=True, max_length=100, null=True, verbose_name='hraje ligu')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hraci/', verbose_name='Fotka')),
                ('datum_narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('info', models.TextField(blank=True, null=True, verbose_name='O mně / Info')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Webové stránky')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
            },
        ),
        migrations.CreateModel(
            name='Soutez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nazev', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('1K', 'Jednokolová'), ('2K', 'Dvoukolová')], default='1K', max_length=2)),
                ('aktivni', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1', models.CharField(choices=[('0:0', '---'), ('6:0', '6:0'), ('6:1', '6:1'), ('6:2', '6:2'), ('6:3', '6:3'), ('6:4', '6:4'), ('7:5', '7:5'), ('7:6', '7:6'), ('0:6', '0:6'), ('1:6', '1:6'), ('2:6', '2:6'), ('3:6', '3:6'), ('4:6', '4:6'), ('5:7', '5:7'), ('6:7', '6:7')], default='0:0', max_length=5)),
                ('set2', models.CharField(choices=[('0:0', '---'), ('6:0', '6:0'), ('6:1', '6:1'), ('6:2', '6:2'), ('6:3', '6:3'), ('6:4', '6:4'), ('7:5', '7:5'), ('7:6', '7:6'), ('0:6', '0:6'), ('1:6', '1:6'), ('2:6', '2:6'), ('3:6', '3:6'), ('4:6', '4:6'), ('5:7', '5:7'), ('6:7', '6:7')], default='0:0', max_length=5)),
                ('set3', models.CharField(blank=True, default='0:0', max_length=10)),
                ('sety_domaci', models.IntegerField(default=0)),
                ('sety_hoste', models.IntegerField(default=0)),
                ('gamy_domaci', models.IntegerField(default=0)),
                ('gamy_hoste', models.IntegerField(default=0)),
                ('mice_bere_domaci', models.BooleanField(default=True, verbose_name='Míče bere domácí')),
                ('odehrano', models.BooleanField(default=False)),
                ('datum', models.DateField(blank=True, null=True, verbose_name='Datum zápasu')),
                ('hrac_domaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci', to='tenis_app.hrac')),
                ('hrac_hoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoste', to='tenis_app.hrac')),
                ('soutez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapasy', to='tenis_app.soutez')),
            ],
            options={
                'ordering': ['-datum', 'hrac_domaci'],
                'unique_together': {('soutez', 'hrac_domaci', 'hrac_hoste')},
            },
        ),
    ]
