# Generated by Django 5.2.8 on 2026-01-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapas',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='sety_domaci',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='sety_hoste',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='skore_detail',
        ),
        migrations.AddField(
            model_name='zapas',
            name='set1_domaci',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S1 Domácí'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set1_hoste',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S1 Hosté'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set2_domaci',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S2 Domácí'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set2_hoste',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S2 Hosté'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set3_domaci',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S3 Domácí'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set3_hoste',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, verbose_name='S3 Hosté'),
        ),
    ]
