# Generated by Django 5.2.8 on 2026-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0002_hrac_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrac',
            name='souteze',
            field=models.ManyToManyField(blank=True, related_name='hraci', to='tenis_app.soutez', verbose_name='Přihlášen do soutěží'),
        ),
    ]
