# Generated by Django 5.2.8 on 2026-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0002_remove_zapas_datum_remove_zapas_sety_domaci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapas',
            name='set1_domaci',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='set1_hoste',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='set2_domaci',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='set2_hoste',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='set3_domaci',
        ),
        migrations.RemoveField(
            model_name='zapas',
            name='set3_hoste',
        ),
        migrations.AddField(
            model_name='zapas',
            name='set1',
            field=models.CharField(choices=[('0:0', '---'), ('6:0', '6:0'), ('6:1', '6:1'), ('6:2', '6:2'), ('6:3', '6:3'), ('6:4', '6:4'), ('7:5', '7:5'), ('7:6', '7:6'), ('0:6', '0:6'), ('1:6', '1:6'), ('2:6', '2:6'), ('3:6', '3:6'), ('4:6', '4:6'), ('5:7', '5:7'), ('6:7', '6:7')], default='0:0', max_length=5),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set2',
            field=models.CharField(choices=[('0:0', '---'), ('6:0', '6:0'), ('6:1', '6:1'), ('6:2', '6:2'), ('6:3', '6:3'), ('6:4', '6:4'), ('7:5', '7:5'), ('7:6', '7:6'), ('0:6', '0:6'), ('1:6', '1:6'), ('2:6', '2:6'), ('3:6', '3:6'), ('4:6', '4:6'), ('5:7', '5:7'), ('6:7', '6:7')], default='0:0', max_length=5),
        ),
        migrations.AddField(
            model_name='zapas',
            name='set3',
            field=models.CharField(choices=[('0:0', '---'), ('6:0', '6:0'), ('6:1', '6:1'), ('6:2', '6:2'), ('6:3', '6:3'), ('6:4', '6:4'), ('7:5', '7:5'), ('7:6', '7:6'), ('0:6', '0:6'), ('1:6', '1:6'), ('2:6', '2:6'), ('3:6', '3:6'), ('4:6', '4:6'), ('5:7', '5:7'), ('6:7', '6:7')], default='0:0', max_length=5),
        ),
    ]
