# Generated by Django 5.2.8 on 2026-07-05 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0003_hrac_souteze'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='upraveno_kdy',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zapas',
            name='vytvoreno_kdy',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
