# Generated by Django 5.2.8 on 2026-01-27 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0003_remove_zapas_set1_domaci_remove_zapas_set1_hoste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
