# Generated by Django 5.2.8 on 2026-02-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0004_zapas_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('1K', 'Jednokolová'), ('2K', 'Dvoukolová')], default='2K', max_length=2)),
                ('aktivni', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zapas',
            name='set3',
            field=models.CharField(blank=True, default='0:0', help_text='Pro Supertiebreak zadejte skóre ručně (např. 10:8)', max_length=10),
        ),
        migrations.AddField(
            model_name='zapas',
            name='soutez',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapasy', to='tenis_app.soutez'),
        ),
    ]
