# Generated by Django 5.2.8 on 2026-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0004_zapas_upraveno_kdy_zapas_vytvoreno_kdy'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='poznamka',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='tiebreak_set1',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tiebreak 1. setu'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='tiebreak_set2',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tiebreak 2. setu'),
        ),
        migrations.AddField(
            model_name='zapas',
            name='tiebreak_set3',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Tiebreak 3. setu'),
        ),
    ]
