# Generated by Django 5.2.8 on 2026-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0005_zapas_poznamka_zapas_tiebreak_set1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrac',
            name='adresa',
            field=models.CharField(blank=True, max_length=150, verbose_name='adresa'),
        ),
    ]
