# Generated by Django 5.2.8 on 2026-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0005_soutez_alter_zapas_set3_zapas_soutez'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutez',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='jmeno',
            field=models.CharField(max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='klub',
            field=models.CharField(blank=True, max_length=100, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='soutez',
            name='typ',
            field=models.CharField(choices=[('1K', 'Jednokolová'), ('2K', 'Dvoukolová')], default='1K', max_length=2),
        ),
    ]
