# Generated by Django 5.2.8 on 2026-03-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0006_soutez_slug_alter_hrac_jmeno_alter_hrac_klub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutez',
            name='slug',
            field=models.SlugField(default='hotovo', unique=True),
            preserve_default=False,
        ),
    ]
