# Generated by Django 5.2.8 on 2026-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0007_alter_soutez_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrac',
            options={'verbose_name': 'Hráč', 'verbose_name_plural': 'Hráči'},
        ),
        migrations.RemoveField(
            model_name='hrac',
            name='body',
        ),
        migrations.AddField(
            model_name='hrac',
            name='datum_narozeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum narození'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hraci/', verbose_name='Fotka'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='O mně / Info'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='hrac',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Webové stránky'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='jmeno',
            field=models.CharField(max_length=100, verbose_name='Jméno a příjmení'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='klub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domovský klub'),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='set3',
            field=models.CharField(blank=True, default='0:0', max_length=10),
        ),
    ]
