# Generated by Django 5.2.8 on 2026-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0008_alter_hrac_options_remove_hrac_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='mice_bere_domaci',
            field=models.BooleanField(default=True, verbose_name='Míče bere domácí'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='klub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='hraje ligu'),
        ),
    ]
