# Generated by Django 5.2.8 on 2026-04-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0009_zapas_mice_bere_domaci_alter_hrac_klub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapas',
            name='mice_bere_domaci',
        ),
    ]
