# Generated by Django 5.2.8 on 2026-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis_app', '0010_remove_zapas_mice_bere_domaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='mice_bere_domaci',
            field=models.BooleanField(default=True, verbose_name='Míče bere domácí'),
        ),
    ]
