# Generated by Django 5.2.8 on 2026-03-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('datum_narozeni', models.DateField()),
                ('email_rodice', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('kategorie', models.CharField(choices=[('U9', 'Mladší přípravka'), ('U11', 'Starší přípravka'), ('U13', 'Mladší žáci'), ('U15', 'Starší žáci'), ('MUZ', 'Muži')], max_length=3)),
                ('variabilni_symbol', models.PositiveIntegerField(help_text='ID pro párování plateb', unique=True)),
                ('aktivni', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Člen',
                'verbose_name_plural': 'Členové',
            },
        ),
        migrations.CreateModel(
            name='PlatbaPrispevku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezona', models.CharField(help_text='Např. Podzim 2026', max_length=20)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datum_splatnosti', models.DateField()),
                ('zaplaceno', models.BooleanField(default=False)),
                ('datum_uhrady', models.DateField(blank=True, null=True)),
                ('clen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platby', to='fotbal_app.clen')),
            ],
            options={
                'verbose_name': 'Platba',
                'verbose_name_plural': 'Platby',
            },
        ),
    ]
